layout de producao
JessMotta/report_production_systems pull request #15
Opened 2020-08-27 20:07 UTC by leolima21

Escrevi o texto da parte de layout de procuao ( cap  8

2020-08-27 22:34 UTC, JessMotta requested changes
Por favor faça as correções pontuadas

2020-08-27 22:38 UTC, JessMotta requested changes

2020-08-27 22:38 UTC, JessMotta commented on sections/08parranjofisico.tex
> +Arranjo físico ou lay-out dos equipamentos, é a disposição que os equipamentos possuem na fábrica, de modo que proporcionem a máxima eficiência dentro do processo produtivo.
creio que nesse caso o verbo "é" não fica separado por vírgula

2020-08-27 22:38 UTC, JessMotta commented on sections/08parranjofisico.tex
> +OS principais tipos de arranjos físicos são o Posicional ou fixo, arranjo em que os equipamentos e operadores movem-se durante as operações; Físico por Processo, onde os equipamentos possuem posicion
Os está as duas letras em maiusculo
pode colocar as palavras em mínusculo, usa : para separar o nome do que é

2020-08-28 11:48 UTC, leolima21 commented on sections/08parranjofisico.tex
> +OS principais tipos de arranjos físicos são o Posicional ou fixo, arranjo em que os equipamentos e operadores movem-se durante as operações; Físico por Processo, onde os equipamentos possuem posicion
nesse caso tem q ser maiusculo msm pq é um nome próprio

2020-08-28 14:06 UTC, JessMotta approved these changes
PR aprovado, correções realizadas

2020-08-28 14:06 UTC, merged